=== RobustUI/RobustUI-electron/src/app/schemas/composite-component.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1613469890.json",
  "title": "2",
  "type": "object",
  "required": [
    "label",
    "type",
    "components",
    "inputs",
    "outputs",
    "positions"
  ],
  "properties": {
    "label": {
      "$id": "#root/label",
      "title": "Label",
      "type": "string",
      "default": "",
      "pattern": "^.*$"
    },
    "type": {
      "$id": "#root/type",
      "title": "Type",
      "type": "integer",
      "default": 0
    },
    "components": {
      "$id": "#root/components",
      "title": "Components",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/components/items",
        "title": "Items",
        "type": "object",
        "required": [
          "label",
          "type"
        ],
        "properties": {
          "label": {
            "$id": "#root/components/items/label",
            "title": "Label",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "type": {
            "$id": "#root/components/items/type",
            "title": "Type",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          }
        }
      }

    },
    "inputs": {
      "$id": "#root/inputs",
      "title": "Inputs",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/inputs/items",
        "title": "Items",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      }
    },
    "outputs": {
      "$id": "#root/outputs",
      "title": "Outputs",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/outputs/items",
        "title": "Items",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      }
    },
    "positions": {
      "$id": "#root/positions",
      "title": "Positions",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/positions/items",
        "title": "Items",
        "type": "object",
        "required": [
          "label",
          "x",
          "y",
          "width"
        ],
        "properties": {
          "label": {
            "$id": "#root/positions/items/label",
            "title": "Label",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "x": {
            "$id": "#root/positions/items/x",
            "title": "X",
            "type": "number",
            "default": 0
          },
          "y": {
            "$id": "#root/positions/items/y",
            "title": "Y",
            "type": "number",
            "default": 0
          },
          "width": {
            "$id": "#root/positions/items/width",
            "title": "Width",
            "type": "number",
            "default": 0
          }
        }
      }

    }
  }
}

=== RobustUI/RobustUI-electron/src/app/JSON/componentuseCaseThree.json
{
      "label": "useCaseThree",
      "type": 2,
      "components": [
        {
      "label": "toggle",
      "type": "Toggle"
      },{
      "label": "content",
      "type": "toggleSelective"
      }
      ],
      "inputs": [
        
      ],
      "outputs": [
        
      ],
      "positions": [
        {
      "label": "toggle",
      "x": 0,
      "y": 0,
      "width": 486
      },{
      "label": "content",
      "x": 0,
      "y": 0,
      "width": 486
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentThis is a composite component.json
{
      "label": "This is a composite component",
      "type": 2,
      "components": [
        {
      "label": "TheLabel",
      "type": "Murden"
      }
      ],
      "inputs": [
        
      ],
      "outputs": [
        
      ],
      "positions": [
        {
      "label": "TheLabel",
      "x": 164,
      "y": 204,
      "width": 50
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentDropDownComp.json
{
      "label": "DropDownComp",
      "type": 2,
      "components": [
        {
      "label": "toggle",
      "type": "dropdown"
      },{
      "label": "history",
      "type": "dropdownElement"
      },{
      "label": "contact",
      "type": "dropdownElement"
      },{
      "label": "jobs",
      "type": "dropdownElement"
      }
      ],
      "inputs": [
        
      ],
      "outputs": [
        
      ],
      "positions": [
        {
      "label": "toggle",
      "x": 0,
      "y": 0,
      "width": 486
      },{
      "label": "history",
      "x": 0,
      "y": 0,
      "width": 486
      },{
      "label": "contact",
      "x": 0,
      "y": 0,
      "width": 486
      },{
      "label": "jobs",
      "x": 0,
      "y": 0,
      "width": 486
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentfaq.json
{
      "label": "faq",
      "type": 2,
      "components": [
        {
      "label": "Q1",
      "type": "Toggle"
      },{
      "label": "Q2",
      "type": "Toggle"
      },{
      "label": "Q3",
      "type": "Toggle"
      }
      ],
      "inputs": [
        
      ],
      "outputs": [
        
      ],
      "positions": [
        {
      "label": "Q1",
      "x": 0,
      "y": 0,
      "width": 320.6666666666667
      },{
      "label": "Q2",
      "x": 0,
      "y": 0,
      "width": 320.6666666666667
      },{
      "label": "Q3",
      "x": 0,
      "y": 0,
      "width": 320.6666666666667
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentComposite_A.json
{
      "label": "Composite_A",
      "type": 2,
      "components": [
        {
      "label": "Hello",
      "type": "A"
      },{
      "label": "Foo",
      "type": "A"
      },{
      "label": "World",
      "type": "B"
      }
      ],
      "inputs": [
        "awk"
      ],
      "outputs": [
        "msg"
      ],
      "positions": [
        {
      "label": "Hello",
      "x": 40,
      "y": 200,
      "width": 200
      },{
      "label": "World",
      "x": 100,
      "y": 40,
      "width": 25
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentsmallyo.json
{
      "label": "smallyo",
      "type": 2,
      "components": [
        {
      "label": "ayyy",
      "type": "A"
      },{
      "label": "byyyy",
      "type": "B"
      }
      ],
      "inputs": [
        
      ],
      "outputs": [
        
      ],
      "positions": [
        {
      "label": "ayyy",
      "x": 0,
      "y": 0,
      "width": 624.5
      },{
      "label": "byyyy",
      "x": 0,
      "y": 0,
      "width": 624.5
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentChat.json
{
      "label": "Chat",
      "type": 2,
      "components": [
        {
      "label": "ChatBox",
      "type": "ChatBox"
      },{
      "label": "MessageService",
      "type": "MessageService"
      }
      ],
      "inputs": [
        
      ],
      "outputs": [
        
      ],
      "positions": [
        {
      "label": "ChatBox",
      "x": 0,
      "y": 0,
      "width": 491
      },{
      "label": "MessageService",
      "x": 0,
      "y": 0,
      "width": 491
      }
      ]
    }
