=== RobustUI/RobustUI-electron/src/app/schemas/selective-component.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1614245601.json",
  "title": "3",
  "type": "object",
  "required": [
    "label",
    "type",
    "observer",
    "cases",
    "inputs",
    "outputs",
    "positions"
  ],
  "properties": {
    "label": {
      "$id": "#root/label",
      "title": "Label",
      "type": "string",
      "default": "",
      "pattern": "^.*$"
    },
    "type": {
      "$id": "#root/type",
      "title": "Type",
      "type": "integer",
      "default": 0
    },
    "observer": {
      "$id": "#root/observer",
      "title": "Observer",
      "type": "object",
      "required": [
        "input",
        "dataType"
      ],
      "properties": {
        "input": {
          "$id": "#root/observer/input",
          "title": "Input",
          "type": "string",
          "default": "",
          "pattern": "^.*$"
        },
        "dateType": {
          "$id": "#root/observer/dataType",
          "title": "Datatype",
          "type": "string",
          "default": "",
          "pattern": "^.*$"
        }
      }
    }
  ,
    "cases": {
      "$id": "#root/cases",
      "title": "Cases",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/cases/items",
        "title": "Items",
        "type": "object",
        "required": [
          "guard",
          "type"
        ],
        "properties": {
          "guard": {
            "$id": "#root/cases/items/guard",
            "title": "Guard",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "type": {
            "$id": "#root/cases/items/type",
            "title": "Type",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          }
        }
      }

    },
    "inputs": {
      "$id": "#root/inputs",
      "title": "Inputs",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/inputs/items",
        "title": "Items",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      }
    },
    "outputs": {
      "$id": "#root/outputs",
      "title": "Outputs",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/outputs/items",
        "title": "Items",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      }
    },
    "positions": {
      "$id": "#root/positions",
      "title": "Positions",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/positions/items",
        "title": "Items",
        "type": "object",
        "required": [
          "label",
          "x",
          "y",
          "width"
        ],
        "properties": {
          "label": {
            "$id": "#root/positions/items/label",
            "title": "Label",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "x": {
            "$id": "#root/positions/items/x",
            "title": "X",
            "type": "number",
            "default": 0
          },
          "y": {
            "$id": "#root/positions/items/y",
            "title": "Y",
            "type": "number",
            "default": 0
          },
          "width": {
            "$id": "#root/positions/items/width",
            "title": "Width",
            "type": "number",
            "default": 0
          }
        }
      }

    }
  }
}

=== RobustUI/RobustUI-electron/src/app/JSON/componentAwesomeSelective.json
{
      "label": "AwesomeSelective",
      "type": 3,
      "observer": {
      "input": "valuestream",
      "dataType": "number"
    },
      "cases": [
        {
      "guard": ">=10",
      "label": "Light",
      "type": "onOffComponent"
      },{
      "guard": "<= 9",
      "label": "Lock",
      "type": "onOffComponent"
      }
      ],
      "inputs": [
        "valuestream"
      ],
      "outputs": [
        
      ],
      "positions": [
        {
      "label": "Light",
      "x": 0,
      "y": 0,
      "width": 893
      },{
      "label": "Lock",
      "x": 0,
      "y": 0,
      "width": 893
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentI am Selective.json
{
      "label": "I am Selective",
      "type": 3,
      "observer": {
      "input": "onSelect",
      "dataType": "number"
    },
      "cases": [
        {
      "guard": "<9",
      "type": "Murden"
      },{
      "guard": ">=9",
      "type": "A"
      }
      ],
      "inputs": [
        "onSelect"
      ],
      "outputs": [
        
      ],
      "positions": [
        {
      "label": "Murden",
      "x": 10,
      "y": 10,
      "width": 50
      },{
      "label": "A",
      "x": 10,
      "y": 80,
      "width": 50
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentCSGO.json
{
      "label": "CSGO",
      "type": 3,
      "observer": {
      "input": "stream",
      "dataType": "number"
    },
      "cases": [
        {
      "guard": ">10",
      "type": "I am Selective"
      }
      ],
      "inputs": [
        "stream"
      ],
      "outputs": [
        
      ],
      "positions": [
        {
      "label": "I am Selective",
      "x": 0,
      "y": 0,
      "width": 618.5
      }
      ]
    }
