=== RobustUI/RobustUI-electron/src/app/schemas/simple-component.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1612866524.json",
  "title": "1",
  "type": "object",
  "required": [
    "label",
    "initialState",
    "states",
    "events",
    "inputs",
    "outputs",
    "transitions",
    "positions"
  ],
  "properties": {
    "type": {
      "$id": "#root/type",
      "title": "Type",
      "type": "number",
      "default": "",
      "pattern": "^.*$"
    },
    "type": {
      "$id": "#root/type",
      "title": "Type",
      "type": "number",
      "default": ""
    },
    "label": {
      "$id": "#root/label",
      "title": "Label",
      "type": "string",
      "default": "",
      "pattern": "^.*$"
    },
    "initialState": {
      "$id": "#root/initialState",
      "title": "Initialstate",
      "type": "string",
      "default": "",
      "pattern": "^.*$"
    },
    "states": {
      "$id": "#root/states",
      "title": "States",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/states/items",
        "title": "Items",
        "type": "object",
        "required": [
          "label",
          "type"
        ],
        "properties": {
          "label": {
            "$id": "#root/states/items/label",
            "title": "Label",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "type": {
            "$id": "#root/states/items/type",
            "title": "Type",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          }
        }
      }

    },
    "events": {
      "$id": "#root/events",
      "title": "Events",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/events/items",
        "title": "Items",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      }
    },
    "inputs": {
      "$id": "#root/inputs",
      "title": "Inputs",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/inputs/items",
        "title": "Items",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      }
    },
    "outputs": {
      "$id": "#root/outputs",
      "title": "Outputs",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/outputs/items",
        "title": "Items",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      }
    },
    "transitions": {
      "$id": "#root/transitions",
      "title": "Transitions",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/transitions/items",
        "title": "Items",
        "type": "object",
        "required": [
          "from",
          "label",
          "to"
        ],
        "properties": {
          "from": {
            "$id": "#root/transitions/items/from",
            "title": "From",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "label": {
            "$id": "#root/transitions/items/label",
            "title": "Label",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "to": {
            "$id": "#root/transitions/items/to",
            "title": "To",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          }
        }
      }

    },
    "positions": {
      "$id": "#root/positions",
      "title": "Positions",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/positions/items",
        "title": "Items",
        "type": "object",
        "required": [
          "label",
          "x",
          "y",
          "width"
        ],
        "properties": {
          "label": {
            "$id": "#root/positions/items/label",
            "title": "Label",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "x": {
            "$id": "#root/positions/items/x",
            "title": "X",
            "type": "number",
            "default": 0
          },
          "y": {
            "$id": "#root/positions/items/y",
            "title": "Y",
            "type": "number",
            "default": 0
          },
          "width": {
            "$id": "#root/positions/items/width",
            "title": "Width",
            "type": "integer",
            "default": 0
          }
        }
      }

    }
  }
}

=== RobustUI/RobustUI-electron/src/app/JSON/componentoldcol.json
{
      "label": "oldcol",
      "type": 1,
      "initialState": "initial_state",
      "states": [
        {
      "label": "initial_state",
      "type": "0"
      }
      ],
      "events": [
        
      ],
      "inputs": [
        
      ],
      "outputs": [
        
      ],
      "transitions": [
       
      ],
      "positions": [
        {
      "label": "initial_state",
      "x": 10,
      "y": 10,
      "width": 50
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentdropdown.json
{
      "label": "dropdown",
      "type": 1,
      "initialState": "notShow",
      "states": [
        {
      "label": "notShow",
      "type": "0"
      },{
      "label": "show",
      "type": "0"
      }
      ],
      "events": [
        "click"
      ],
      "inputs": [
        "close"
      ],
      "outputs": [
        
      ],
      "transitions": [
       {
      "anchorPoint": {
          "x": 270.5499,
          "y": 393.05645000000004
        },
      "from": "notShow",
      "label": "click",
      "to": "show"
      },{
      "anchorPoint": {
          "x": 318.85634999999996,
          "y": 309.94355
        },
      "from": "show",
      "label": "click",
      "to": "notShow"
      },{
      "anchorPoint": {
          "x": 353.08835,
          "y": 249.94035000000002
        },
      "from": "show",
      "label": "close",
      "to": "notShow"
      }
      ],
      "positions": [
        {
      "label": "notShow",
      "x": 162,
      "y": 278,
      "width": 50
      },{
      "label": "show",
      "x": 411.40625,
      "y": 356,
      "width": 50
      }
      ]
    }
