=== RobustUI/RobustUI-electron/src/app/schemas/simple-component.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1612866524.json",
  "title": "1",
  "type": "object",
  "required": [
    "label",
    "initialState",
    "states",
    "events",
    "inputs",
    "outputs",
    "transitions",
    "positions"
  ],
  "properties": {
    "type": {
      "$id": "#root/type",
      "title": "Type",
      "type": "number",
      "default": "",
      "pattern": "^.*$"
    },
    "type": {
      "$id": "#root/type",
      "title": "Type",
      "type": "number",
      "default": ""
    },
    "label": {
      "$id": "#root/label",
      "title": "Label",
      "type": "string",
      "default": "",
      "pattern": "^.*$"
    },
    "initialState": {
      "$id": "#root/initialState",
      "title": "Initialstate",
      "type": "string",
      "default": "",
      "pattern": "^.*$"
    },
    "states": {
      "$id": "#root/states",
      "title": "States",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/states/items",
        "title": "Items",
        "type": "object",
        "required": [
          "label",
          "type"
        ],
        "properties": {
          "label": {
            "$id": "#root/states/items/label",
            "title": "Label",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "type": {
            "$id": "#root/states/items/type",
            "title": "Type",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          }
        }
      }

    },
    "events": {
      "$id": "#root/events",
      "title": "Events",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/events/items",
        "title": "Items",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      }
    },
    "inputs": {
      "$id": "#root/inputs",
      "title": "Inputs",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/inputs/items",
        "title": "Items",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      }
    },
    "outputs": {
      "$id": "#root/outputs",
      "title": "Outputs",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/outputs/items",
        "title": "Items",
        "type": "string",
        "default": "",
        "pattern": "^.*$"
      }
    },
    "transitions": {
      "$id": "#root/transitions",
      "title": "Transitions",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/transitions/items",
        "title": "Items",
        "type": "object",
        "required": [
          "from",
          "label",
          "to"
        ],
        "properties": {
          "from": {
            "$id": "#root/transitions/items/from",
            "title": "From",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "label": {
            "$id": "#root/transitions/items/label",
            "title": "Label",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "to": {
            "$id": "#root/transitions/items/to",
            "title": "To",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          }
        }
      }

    },
    "positions": {
      "$id": "#root/positions",
      "title": "Positions",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/positions/items",
        "title": "Items",
        "type": "object",
        "required": [
          "label",
          "x",
          "y",
          "width"
        ],
        "properties": {
          "label": {
            "$id": "#root/positions/items/label",
            "title": "Label",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "x": {
            "$id": "#root/positions/items/x",
            "title": "X",
            "type": "number",
            "default": 0
          },
          "y": {
            "$id": "#root/positions/items/y",
            "title": "Y",
            "type": "number",
            "default": 0
          },
          "width": {
            "$id": "#root/positions/items/width",
            "title": "Width",
            "type": "integer",
            "default": 0
          }
        }
      }

    }
  }
}

=== RobustUI/RobustUI-electron/src/app/JSON/componentdropdownElement.json
{
      "label": "dropdownElement",
      "type": 1,
      "initialState": "notSelected",
      "states": [
        {
      "label": "notSelected",
      "type": "0"
      },{
      "label": "Hovered",
      "type": "0"
      }
      ],
      "events": [
        "pointerenter","pointerenter/close!","pointerleave"
      ],
      "inputs": [
        
      ],
      "outputs": [
        "close"
      ],
      "transitions": [
       {
      "anchorPoint": {
          "x": 213.39790000000005,
          "y": 340.81965
        },
      "from": "notSelected",
      "label": "pointerenter",
      "to": "Hovered"
      },{
      "anchorPoint": {
          "x": 398.00835,
          "y": 274.18035000000003
        },
      "from": "Hovered",
      "label": "pointerenter/close!",
      "to": "notSelected"
      },{
      "anchorPoint": {
          "x": 294.00835,
          "y": 329.18035000000003
        },
      "from": "Hovered",
      "label": "pointerleave",
      "to": "notSelected"
      }
      ],
      "positions": [
        {
      "label": "notSelected",
      "x": 133,
      "y": 220,
      "width": 50
      },{
      "label": "Hovered",
      "x": 332.40625,
      "y": 398,
      "width": 50
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentMikkel.json
{
      "label": "Mikkel",
      "type": 1,
      "initialState": "initial_state",
      "states": [
        {
      "label": "initial_state",
      "type": "0"
      },{
      "label": "new state",
      "type": "0"
      }
      ],
      "events": [
        
      ],
      "inputs": [
        
      ],
      "outputs": [
        
      ],
      "transitions": [
       
      ],
      "positions": [
        {
      "label": "initial_state",
      "x": 248,
      "y": 188,
      "width": 50
      },{
      "label": "new state",
      "x": 271.203125,
      "y": 347,
      "width": 50
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentChatBox.json
{
      "label": "ChatBox",
      "type": 1,
      "initialState": "compose_message",
      "states": [
        {
      "label": "compose_message",
      "type": "0"
      },{
      "label": "loading",
      "type": "0"
      }
      ],
      "events": [
        "click/msg!"
      ],
      "inputs": [
        "ack"
      ],
      "outputs": [
        "msg"
      ],
      "transitions": [
       {
      "anchorPoint": {
          "x": 292.42310000000003,
          "y": 388.92550000000006
        },
      "from": "loading",
      "label": "click/msg!",
      "to": "compose_message"
      },{
      "anchorPoint": {
          "x": 202.38939999999997,
          "y": 380.07450000000006
        },
      "from": "compose_message",
      "label": "ack",
      "to": "loading"
      }
      ],
      "positions": [
        {
      "label": "compose_message",
      "x": 238,
      "y": 264,
      "width": 50
      },{
      "label": "loading",
      "x": 263.8125,
      "y": 459,
      "width": 50
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentA.json
{
      "label": "A",
      "type": 1,
      "initialState": "new statedsd",
      "states": [
        {
      "label": "A_dsad",
      "type": "0"
      },{
      "label": "Ads",
      "type": "0"
      },{
      "label": "new statedsd",
      "type": "0"
      }
      ],
      "events": [
        "click/msg!"
      ],
      "inputs": [
        "awk"
      ],
      "outputs": [
        "msg"
      ],
      "transitions": [
       {
      "anchorPoint": {
          "x": 159.8984,
          "y": 93.2152
        },
      "from": "Ads",
      "label": "awk",
      "to": "A_dsad"
      },{
      "anchorPoint": {
          "x": 422.84389999999996,
          "y": 257.5719
        },
      "from": "new statedsd",
      "label": "click/msg!",
      "to": "A_dsad"
      }
      ],
      "positions": [
        {
      "label": "A_dsad",
      "x": 131,
      "y": 233,
      "width": 200
      },{
      "label": "Ads",
      "x": 100,
      "y": 40,
      "width": 25
      },{
      "label": "new statedsd",
      "x": 545.7140522875817,
      "y": 105.77777777777777,
      "width": 50
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentB.json
{
      "label": "B",
      "type": 1,
      "initialState": "B_A",
      "states": [
        {
      "label": "B_A",
      "type": "0"
      },{
      "label": "B_B_B",
      "type": "0"
      }
      ],
      "events": [
        "click","pointerenter/output!"
      ],
      "inputs": [
        
      ],
      "outputs": [
        "output"
      ],
      "transitions": [
       {
      "anchorPoint": {
          "x": 477.0264,
          "y": 398.30080000000004
        },
      "from": "B_A",
      "label": "click",
      "to": "B_B_B"
      },{
      "anchorPoint": {
          "x": 589.9736,
          "y": 354.1992
        },
      "from": "B_B_B",
      "label": "pointerenter/output!",
      "to": "B_A"
      }
      ],
      "positions": [
        {
      "label": "B_A",
      "x": 420,
      "y": 309,
      "width": 24
      },{
      "label": "B_B_B",
      "x": 580,
      "y": 435,
      "width": 83
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentonOffComponent.json
{
      "label": "onOffComponent",
      "type": 1,
      "initialState": "off",
      "states": [
        {
      "label": "off",
      "type": "0"
      },{
      "label": "on",
      "type": "0"
      }
      ],
      "events": [
        "click"
      ],
      "inputs": [
        "onsettoon"
      ],
      "outputs": [
        
      ],
      "transitions": [
       {
      "anchorPoint": {
          "x": 280.01335000000006,
          "y": 242.49737500000003
        },
      "from": "off",
      "label": "click",
      "to": "on"
      },{
      "anchorPoint": {
          "x": 327.18977499999994,
          "y": 415.5026250000001
        },
      "from": "on",
      "label": "click",
      "to": "off"
      },{
      "anchorPoint": {
          "x": 307.01335000000006,
          "y": 312.49737500000003
        },
      "from": "off",
      "label": "onsettoon",
      "to": "on"
      }
      ],
      "positions": [
        {
      "label": "off",
      "x": 115,
      "y": 345,
      "width": 50
      },{
      "label": "on",
      "x": 402.203125,
      "y": 246,
      "width": 50
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentMessageService.json
{
      "label": "MessageService",
      "type": 1,
      "initialState": "wait_for_message",
      "states": [
        {
      "label": "wait_for_message",
      "type": "0"
      },{
      "label": "loading",
      "type": "0"
      }
      ],
      "events": [
        
      ],
      "inputs": [
        "msg"
      ],
      "outputs": [
        "ack"
      ],
      "transitions": [
       {
      "anchorPoint": {
          "x": 321.8918,
          "y": 328.40090000000004
        },
      "from": "wait_for_message",
      "label": "ack",
      "to": "loading"
      },{
      "anchorPoint": {
          "x": 353.9207,
          "y": 368.5991
        },
      "from": "loading",
      "label": "msg",
      "to": "wait_for_message"
      }
      ],
      "positions": [
        {
      "label": "wait_for_message",
      "x": 301,
      "y": 207,
      "width": 50
      },{
      "label": "loading",
      "x": 324.8125,
      "y": 440,
      "width": 50
      }
      ]
    }

=== RobustUI/RobustUI-electron/src/app/JSON/componentToggle.json
{
      "label": "Toggle",
      "type": 1,
      "initialState": "off",
      "states": [
        {
      "label": "off",
      "type": "0"
      },{
      "label": "on",
      "type": "0"
      }
      ],
      "events": [
        "click"
      ],
      "inputs": [
        
      ],
      "outputs": [
        
      ],
      "transitions": [
       {
      "anchorPoint": {
          "x": 227.88639999999998,
          "y": 366.8672000000001
        },
      "from": "off",
      "label": "click",
      "to": "on"
      },{
      "anchorPoint": {
          "x": 363.1136,
          "y": 278.13280000000003
        },
      "from": "on",
      "label": "click",
      "to": "off"
      }
      ],
      "positions": [
        {
      "label": "off",
      "x": 147,
      "y": 194,
      "width": 50
      },{
      "label": "on",
      "x": 390,
      "y": 383,
      "width": 50
      }
      ]
    }
